services:
  neo4j:
    image: neo4j:5.26.0
    container_name: disease-symptom-neo4j-dev2
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}  
      - NEO4J_dbms_logs_debug_level=DEBUG
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - apoc.import.file.enabled=true
      - apoc.export.file.enabled=true
    volumes:
      - ./data/neo4j_data:/data  
      - ./data/neo4j_logs:/logs 
      - ./data/neo4j_dumps:/data/neo4j_dump 
      - ./backend/scripts:/scripts    
      - ./data/neo4j_import:/var/lib/neo4j/import
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:7474 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    volumes:
    - ./data/preprocessed:/app/data/preprocessed
    - ./data/experiments_param_search:/app/data/experiments_param_search
    - ./data/logs:/app/data/logs

  frontend:
    build:
      context: ./frontendPREV
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  streamlit:
    build:
      context: ./backend
      dockerfile: Dockerfile-streamlit
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - neo4j
      - backend
    volumes:
      - ./data/experiments_param_search:/app/data/experiments_param_search